/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientTokenRouteImport } from './routes/client.$token'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReceptionistRouteImport } from './routes/_authenticated/receptionist'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDesignAssistantRouteImport } from './routes/_authenticated/design-assistant'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox.index'
import { Route as AuthenticatedInboxProjectIdRouteImport } from './routes/_authenticated/inbox.$projectId'

const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTokenRoute = ClientTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ClientRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReceptionistRoute =
  AuthenticatedReceptionistRouteImport.update({
    id: '/receptionist',
    path: '/receptionist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignAssistantRoute =
  AuthenticatedDesignAssistantRouteImport.update({
    id: '/design-assistant',
    path: '/design-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxProjectIdRoute =
  AuthenticatedInboxProjectIdRouteImport.update({
    id: '/inbox/$projectId',
    path: '/inbox/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/design-assistant': typeof AuthenticatedDesignAssistantRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/receptionist': typeof AuthenticatedReceptionistRoute
  '/api/chat': typeof ApiChatRoute
  '/client/$token': typeof ClientTokenRoute
  '/inbox/$projectId': typeof AuthenticatedInboxProjectIdRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/design-assistant': typeof AuthenticatedDesignAssistantRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/proposals': typeof AuthenticatedProposalsRoute
  '/receptionist': typeof AuthenticatedReceptionistRoute
  '/api/chat': typeof ApiChatRoute
  '/client/$token': typeof ClientTokenRoute
  '/inbox/$projectId': typeof AuthenticatedInboxProjectIdRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/client': typeof ClientRouteWithChildren
  '/_authenticated/design-assistant': typeof AuthenticatedDesignAssistantRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/receptionist': typeof AuthenticatedReceptionistRoute
  '/api/chat': typeof ApiChatRoute
  '/client/$token': typeof ClientTokenRoute
  '/_authenticated/inbox/$projectId': typeof AuthenticatedInboxProjectIdRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client'
    | '/design-assistant'
    | '/documents'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/receptionist'
    | '/api/chat'
    | '/client/$token'
    | '/inbox/$projectId'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/client'
    | '/design-assistant'
    | '/documents'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/receptionist'
    | '/api/chat'
    | '/client/$token'
    | '/inbox/$projectId'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/client'
    | '/_authenticated/design-assistant'
    | '/_authenticated/documents'
    | '/_authenticated/portal'
    | '/_authenticated/projects'
    | '/_authenticated/proposals'
    | '/_authenticated/receptionist'
    | '/api/chat'
    | '/client/$token'
    | '/_authenticated/inbox/$projectId'
    | '/_authenticated/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClientRoute: typeof ClientRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$token': {
      id: '/client/$token'
      path: '/$token'
      fullPath: '/client/$token'
      preLoaderRoute: typeof ClientTokenRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/receptionist': {
      id: '/_authenticated/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof AuthenticatedReceptionistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design-assistant': {
      id: '/_authenticated/design-assistant'
      path: '/design-assistant'
      fullPath: '/design-assistant'
      preLoaderRoute: typeof AuthenticatedDesignAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/$projectId': {
      id: '/_authenticated/inbox/$projectId'
      path: '/inbox/$projectId'
      fullPath: '/inbox/$projectId'
      preLoaderRoute: typeof AuthenticatedInboxProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDesignAssistantRoute: typeof AuthenticatedDesignAssistantRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedReceptionistRoute: typeof AuthenticatedReceptionistRoute
  AuthenticatedInboxProjectIdRoute: typeof AuthenticatedInboxProjectIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDesignAssistantRoute: AuthenticatedDesignAssistantRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedReceptionistRoute: AuthenticatedReceptionistRoute,
  AuthenticatedInboxProjectIdRoute: AuthenticatedInboxProjectIdRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientRouteChildren {
  ClientTokenRoute: typeof ClientTokenRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientTokenRoute: ClientTokenRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClientRoute: ClientRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
